name: remote_game_api
description: A Flutter implementation of the GameApi that uses a remote http
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  game_api:
    path: ../game_api
  http: ^0.13.5
  rxdart: ^0.27.5

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
