name: very_good_games
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.4

dependencies:
  bloc: ^8.1.0
  bloc_concurrency: ^0.2.0
  cached_network_image: ^3.2.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  game_api:
    path: packages/game_api
  game_repository:
    path: packages/game_repository
  google_fonts: ^3.0.1
  intl: ^0.17.0
  remote_game_api:
    path: packages/remote_game_api

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
