name: very_good_remote_games_api
description: A Flutter implementation of the VeryGoodGamesApi that uses a remote http
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  http: ^0.13.5
  rxdart: ^0.27.5 
  very_good_games_api:
    path: ../very_good_games_api

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1