name: very_good_games

on: [pull_request, push]

jobs:

  verify-game_repository:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    with:
      coverage_excludes: "*.g.dart"
      working_directory: "packages/game_repository"
  
  verify-remote_game_api:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      coverage_excludes: "*.g.dart"
      working_directory: "packages/remote_game_api"
      flutter_channel: stable
      flutter_version: 3.3.4
      min_coverage: 1

  verify-user_api:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    with:
      coverage_excludes: "*.g.dart"
      working_directory: "packages/user_api"
  
  verify-application:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      coverage_excludes: "*.g.dart"
      flutter_channel: stable
      flutter_version: 3.3.4

  verify-semantic-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build:
    needs:
      [
        verify-game_repository,
        verify-remote_game_api,
        verify-user_api,
        verify-application,
        verify-semantic-pull-request,
      ]

    runs-on: ubuntu-latest

    steps:
      - name: noop
        run: echo 'noop'
